### ISSUE TITLE
y-axis values for Emissions

### ISSUE THREAD

**Issue by nickhalmagyi** [opennem/opennem-fe#117]
Hi, I have a small observation

When I land at the Energy site
https://opennem.org.au/energy/nem/?range=7d&interval=30m
then select Emissions
https://opennem.org.au/emissions/au/?interval=Quarter&projections=false&history=false

I find 
* the y-axis values  not correct
* The "Total" tooltip also has incorrect values
* Land Management is deselected
<img width="1317" alt="Emissions" src="https://user-images.githubusercontent.com/22376971/188650727-781db0ee-0641-4da4-87b7-825ee08d1835.png">

When I reload the page, the values are fixed.

**Comment by chienleng** [comment]
@nickhalmagyi
* We've made the decision to de-select Land management on first view because the measurement in that sector is a bit misleading. And without displaying it on first view, it's probably a more accurate picture of Australia's emissions. You can toggle it back to see the differences.
* Issues with total and yAxis are fixed now. Check footer version `v4.11.5`

**Comment by nickhalmagyi** [comment]
>     * We've made the decision to de-select Land management on first view because the measurement in that sector is a bit misleading. And without displaying it on first view, it's probably a more accurate picture of Australia's emissions. You can toggle it back to see the differences.

Thanks, makes sense. In fact after seeing this visualization  I went down a rabbit hole trying to make sense of the large negative CO2 emission from Land Management. I think I understand fairly well now, it certainly is contentious.
